server:
  host: "0.0.0.0"
  port: 8080

database:
  host: "localhost"
  port: 5432
  user: "agentmesh"
  password: "agentmesh"
  dbname: "agentmesh"
  sslmode: "disable"

heartbeat:
  interval_seconds: 30
  timeout_seconds: 90

distributor:
  rebalance_interval_seconds: 60
